// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExtractQuestions(arg1) {
  return window['go']['main']['App']['ExtractQuestions'](arg1);
}

export function ProcessPDF(arg1) {
  return window['go']['main']['App']['ProcessPDF'](arg1);
}

export function ProcessQuestion(arg1) {
  return window['go']['main']['App']['ProcessQuestion'](arg1);
}
