// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExtractQuestions(arg1:string):Promise<Array<string>>;

export function ProcessPDF(arg1:string):Promise<Record<string, any>>;

export function ProcessQuestion(arg1:string):Promise<string>;
